// Analytics Domain — 40+ intents (EN + Hindi/Hinglish)
export const analyticsIntents = [
  // === SALES ===
  { id: 'sales_today', category: 'analytics', keywords: ['sales today','today sales','todays revenue','aaj ki sales','aaj kitna bikaa','today revenue','todays earnings','aaj ka revenue','aaj kitna kamaya','sales of today'], response: { text: "Let me check today's sales for you...", action: { type: 'data_query', handler: 'getChatSalesData' } }, followUp: ['Show pending orders', 'What are my top products?'] },
  { id: 'sales_this_month', category: 'analytics', keywords: ['sales this month','monthly sales','month sales','this month revenue','is mahine ki sales','mahine ki kamai','monthly revenue','is month kitna bika','month ka revenue','sales report'], response: { text: "Let me pull your monthly sales data...", action: { type: 'data_query', handler: 'getChatSalesData' } }, followUp: ['Compare with last month', 'What are my top sellers?', 'How many orders this month?'] },
  { id: 'sales_this_week', category: 'analytics', keywords: ['sales this week','weekly sales','week sales','is hafte ki sales','hafte ki kamai','weekly revenue','this week revenue','week ka data'], response: { text: "Let me check this week's sales...", action: { type: 'data_query', handler: 'getChatSalesData' } }, followUp: ['Show daily breakdown', 'Compare with last week'] },
  { id: 'total_revenue', category: 'analytics', keywords: ['total revenue','all time sales','total sales','overall revenue','total kamai','ab tak kitna bika','total earnings','all time revenue','lifetime sales','puri sales'], response: { text: "Let me get your total revenue data...", action: { type: 'data_query', handler: 'getChatSalesData' } }, followUp: ['Set a monthly target', 'What are my top products?'] },

  // === TOP PRODUCTS ===
  { id: 'top_products', category: 'analytics', keywords: ['top products','best sellers','best selling','most sold','popular products','sabse zyada kya bika','top seller','best performer','top selling product','popular item','konsa product zyada bika','hit product'], response: { text: "Let me find your best sellers...", action: { type: 'data_query', handler: 'getChatTopProducts' } }, followUp: ['Show sales this month', 'Any out of stock products?'] },
  { id: 'worst_products', category: 'analytics', keywords: ['worst products','least sold','not selling','slow products','low performer','kya nahi bik raha','konsa product nahi bik raha','slow moving','poor selling'], response: { text: "Let me check your product performance data...", action: { type: 'data_query', handler: 'getChatTopProducts' } }, followUp: ['How to improve sales?', 'Show top sellers'] },

  // === TRAFFIC / VISITORS ===
  { id: 'traffic', category: 'analytics', keywords: ['traffic','visitors','page views','views','website traffic','site visitors','kitne log aaye','visitors kitne hain','traffic kitna hai','views kitne hain','website pe kitne log aaye','page views kitne'], response: { text: "Let me check your visitor stats...", action: { type: 'data_query', handler: 'getChatVisitorData' } }, followUp: ['What are my sales?', 'How to get more visitors?'] },
  { id: 'visitor_count', category: 'analytics', keywords: ['how many visitors','visitor count','total visitors','unique visitors','kitne visitor aaye','total visitors kitne','unique log kitne aaye'], response: { text: "Let me check your visitor data...", action: { type: 'data_query', handler: 'getChatVisitorData' } }, followUp: ['How to get more traffic?', 'What are my sales?'] },
  { id: 'get_more_traffic', category: 'analytics', keywords: ['get more traffic','increase visitors','more customers','how to get customers','traffic kaise badhaye','customer kaise laaye','visitors kaise badhaye','marketing tips','promote store'], response: { text: "**Tips to increase traffic:** 🚀\n\n1. **Share on WhatsApp** — Send your store link to contacts\n2. **Social Media** — Post on Instagram/Facebook daily\n3. **WhatsApp Status** — Update your status with product photos\n4. **Google** — Your store gets indexed automatically\n5. **Word of mouth** — Tell friends & family to share\n6. **Offer discounts** — Create offers to attract first-time buyers\n\nYour store link: Check **Profile** → **Site URL**", action: null }, followUp: ['How to create an offer?', 'What is my store link?'] },

  // === AOV ===
  { id: 'average_order', category: 'analytics', keywords: ['average order value','aov','average order','average sale','average order kitna hai','avg order value','per order average'], response: { text: "You can find your **Average Order Value (AOV)** on the Dashboard:\n1. Go to **Dashboard**.\n2. Look at the **Average Order Value** card.\n3. It shows current AOV and comparison with previous period.\n\n**Tip:** To increase AOV, try offering free delivery above a certain amount!", action: { type: 'navigate', label: 'Go to Dashboard', url: '/dashboard' } }, followUp: ['How to increase AOV?', 'Show sales this month'] },
  { id: 'increase_aov', category: 'analytics', keywords: ['increase aov','increase order value','bigger orders','more per order','aov kaise badhaye','order value kaise badhaye','per order zyada'], response: { text: "**Tips to increase Average Order Value:**\n\n1. **Free delivery threshold** — \"Free delivery on orders above ₹500\"\n2. **Bundle products** — Create product bundles/combos\n3. **Offer discounts on bulk** — \"Buy 2 Get 10% Off\"\n4. **Upsell related products** — Show complementary items\n5. **Limited time offers** — Create urgency\n\nSet up delivery thresholds in **Profile** → **Delivery Settings**!", action: { type: 'navigate', label: 'Go to Profile', url: '/dashboard/profile' } }, followUp: ['How to set delivery threshold?', 'How to create offers?'] },

  // === MONTHLY TARGET ===
  { id: 'set_target', category: 'analytics', keywords: ['set target','monthly target','sales target','revenue target','target set karo','mahine ka target','sales goal','revenue goal','target kaise set kare','laxya set karo'], response: { text: "To set a monthly sales target:\n1. Go to **Analytics** page.\n2. Look for the **Monthly Target** section.\n3. Enter your target revenue amount.\n4. Save.\n\nYou'll see a progress bar showing how close you are to your goal! 📊", action: { type: 'navigate', label: 'Go to Analytics', url: '/dashboard/analytics' } }, followUp: ['What are my sales this month?', 'How to increase sales?'] },
  { id: 'am_i_on_track', category: 'analytics', keywords: ['am i on track','target progress','goal progress','on track','kitna complete hua','target pe hain kya','goal tak pahunche','progress kya hai'], response: { text: "Let me check your sales progress against your target...", action: { type: 'data_query', handler: 'getChatSalesData' } }, followUp: ['Show top products', 'How to increase sales?'] },

  // === EXPORT DATA ===
  { id: 'export_data', category: 'analytics', keywords: ['export data','download data','csv download','data export','export analytics','data download karo','data nikalo','csv banao','data export kaise kare','download report','analytics download'], response: { text: "To export your data:\n1. Go to **Dashboard** page.\n2. Click the **Export CSV** button (top right).\n3. Select what you want to export.\n4. Download the file.\n\nYou can open CSV files in **Excel** or **Google Sheets**!", action: { type: 'navigate', label: 'Go to Dashboard', url: '/dashboard' } }, followUp: ['Show sales data', 'Show order data'] },

  // === COMPARISON ===
  { id: 'sales_comparison', category: 'analytics', keywords: ['compare sales','last month comparison','sales vs last month','pichle mahine se compare','comparison','growth','sales badhi ya nahi','performance comparison','month on month'], response: { text: "To compare sales periods:\n1. Go to **Dashboard**.\n2. Each stat card shows **% change** vs the previous period.\n3. Use the **Filter** button to change the time period (7 days, 30 days, 3 months).\n\nGreen ↑ means growth, Red ↓ means decline.", action: { type: 'navigate', label: 'Go to Dashboard', url: '/dashboard' } }, followUp: ['What are my sales this month?', 'Show top products'] },

  // === TIPS ===
  { id: 'increase_sales', category: 'analytics', keywords: ['increase sales','more sales','boost sales','sales badhao','sales kaise badhaye','zyada sales kaise ho','how to sell more','tips for more sales','sales tips','grow business'], response: { text: "**Tips to boost your sales:** 🚀\n\n1. **Add quality photos** — Clear, bright product images\n2. **Write good descriptions** — Highlight benefits, not just features\n3. **Competitive pricing** — Check what others charge\n4. **Share daily on WhatsApp** — Status updates with products\n5. **Create offers** — Discounts attract new buyers\n6. **Post on Instagram** — Use product reels\n7. **Ask for reviews** — Social proof builds trust\n8. **Respond fast** — Quick replies = more sales\n\nNeed help with any of these? Just ask! 😊", action: null }, followUp: ['How to create an offer?', 'How to share my store?', 'How to get more traffic?'] },
  { id: 'improve_store', category: 'analytics', keywords: ['improve store','better website','optimize store','store better kaise kare','website kaise improve kare','store optimize karo','make store better','website acchi kaise banaye'], response: { text: "**Quick wins to improve your store:**\n\n✅ Add a **clear logo** — builds brand identity\n✅ Write a **compelling About section** — tell your story\n✅ Use **high-quality product photos** — first impressions matter\n✅ Set **competitive prices** — research your market\n✅ Add **product descriptions** — help customers decide\n✅ Enable **multiple product images** — show different angles\n✅ Create **categories** — organize your products\n✅ Add **social media links** — build your following\n\nWant me to help with any of these? 😊", action: null }, followUp: ['Help me write about section', 'How to upload better photos?', 'How to add categories?'] },
];
