// Billing & Payments — 45+ intents (EN + Hindi/Hinglish)
export const billingIntents = [
  // === UPI / PAYMENT SETUP ===
  { id: 'setup_upi', category: 'billing', keywords: ['setup upi','add upi','upi id','upi setup','payment setup','upi set karo','upi id daalo','upi kaise lagaye','payment method set','upi configure','upi id add karo'], response: { text: "To set up your UPI ID:\n1. Go to **Profile** settings.\n2. Find the **UPI ID** field.\n3. Enter your UPI ID (e.g., yourname@paytm, yourname@upi).\n4. Save.\n\nCustomers will pay you **directly** via UPI — we don't hold any money! 💰", action: { type: 'navigate', label: 'Go to Profile', url: '/dashboard/profile' } }, followUp: ['How to set up COD?', 'How does payment work?'] },
  { id: 'change_upi', category: 'billing', keywords: ['change upi','update upi','new upi','upi badle','upi change karo','upi update karo','different upi','naya upi id'], response: { text: "To change your UPI ID:\n1. Go to **Profile** settings.\n2. Update the **UPI ID** field with your new UPI.\n3. Save.\n\nThe new UPI will be used for all future payments.", action: { type: 'navigate', label: 'Go to Profile', url: '/dashboard/profile' } }, followUp: ['How does payment work?', 'How to set delivery charges?'] },
  { id: 'setup_cod', category: 'billing', keywords: ['setup cod','cash on delivery','cod setup','cod enable','cod karo','cash on delivery kaise kare','cod kaise lagaye','cod set karo'], response: { text: "To enable Cash on Delivery (COD):\n1. Go to **Profile** settings.\n2. In payment settings, you can choose **COD Only** mode.\n3. Save.\n\n⚠️ With COD, you're responsible for collecting payment upon delivery.", action: { type: 'navigate', label: 'Go to Profile', url: '/dashboard/profile' } }, followUp: ['How to set up UPI?', 'How does payment work?'] },
  { id: 'how_payment_works', category: 'billing', keywords: ['how payment works','payment process','payment system','payment kaise hota hai','payment flow','how customers pay','payment method','customer kaise pay karta hai'], response: { text: "**How payments work on BizVistar:**\n1. Customer places an order on your store.\n2. They pay you **directly via UPI** (we redirect them to your UPI).\n3. The payment goes straight to **your account** — we don't hold it!\n4. You verify the payment and mark the order as **Paid**.\n\n**We charge ZERO commission on sales.** 🎉", action: null }, followUp: ['How to set up UPI?', 'How to verify payment?'] },

  // === SUBSCRIPTION / PLAN ===
  { id: 'my_plan', category: 'billing', keywords: ['my plan','current plan','which plan','what plan','subscription status','plan kya hai','mera plan','konsa plan hai','subscription details','plan details','my subscription','mera subscription'], response: { text: "Let me check your plan details...", action: { type: 'data_query', handler: 'getChatSubscriptionData' } }, followUp: ['How to upgrade?', 'What are the plan options?'] },
  { id: 'pricing', category: 'billing', keywords: ['pricing','cost','price','how much','kitna paisa','kitna lagega','kya rate hai','plan price','subscription cost','monthly cost','fees','charges'], response: { text: "**BizVistar Pricing:**\n\n🔥 **Founding Member Offer:** ₹399/mo (50% OFF!)\n📌 Standard Price: ₹799/mo\n\n**What's included:**\n- Unlimited products (on Pro/Growth)\n- Beautiful website templates\n- Order management\n- Analytics dashboard\n- Zero commission on sales!\n\nThis founding member price is locked forever! 🎉", action: { type: 'navigate', label: 'View Pricing', url: '/pricing' } }, followUp: ['How to subscribe?', 'Is there a free trial?'] },
  { id: 'free_trial', category: 'billing', keywords: ['free trial','trial period','try free','free plan','muft trial','free me try karo','trial hai kya','free version','trial period kitna hai'], response: { text: "Yes! You can explore the dashboard, add products, and set up your store **before subscribing**.\n\nTo **publish** your website and go live, you'll need an active subscription (₹399/mo founding member price).\n\nAll your data is saved even before subscribing!", action: { type: 'navigate', label: 'View Pricing', url: '/pricing' } }, followUp: ['How to subscribe?', 'What\'s included in the plan?'] },
  { id: 'plan_comparison', category: 'billing', keywords: ['plan comparison','compare plans','which plan is best','starter vs pro','pro vs growth','plan difference','plans me kya fark hai','konsa plan lena chahiye','best plan'], response: { text: "**Plan Comparison:**\n\n| Feature | Starter | Pro | Growth |\n|---|---|---|---|\n| Products | 25 | Unlimited | Unlimited |\n| Template Changes | ❌ | 1/month | Unlimited |\n| Analytics | Basic | Full | Full |\n| Commission | 0% | 0% | 0% |\n\n**Recommendation:** Start with Pro — it covers everything most sellers need! 🚀", action: { type: 'navigate', label: 'View Plans', url: '/pricing' } }, followUp: ['How to upgrade?', 'How to subscribe?'] },

  // === UPGRADE / DOWNGRADE ===
  { id: 'upgrade_plan', category: 'billing', keywords: ['upgrade plan','upgrade subscription','better plan','higher plan','plan upgrade karo','plan badhao','upgrade kaise kare','plan change karo','zyada features chahiye'], response: { text: "To upgrade your plan:\n1. Go to **Profile** settings.\n2. Click on **Subscription/Plan** section.\n3. Select the plan you want to upgrade to.\n4. Complete the payment.\n\nYour upgrade takes effect immediately! All your data is preserved. 🎉", action: { type: 'navigate', label: 'Go to Profile', url: '/dashboard/profile' } }, followUp: ['What are the plan options?', 'How much does it cost?'] },
  { id: 'downgrade_plan', category: 'billing', keywords: ['downgrade plan','lower plan','cheaper plan','plan downgrade','kam wala plan','sasta plan','downgrade kaise kare'], response: { text: "To downgrade your plan, please contact our support team via WhatsApp. We'll help you switch to a lower plan.\n\n⚠️ **Note:** Downgrading may reduce your product limit and feature access.", action: { type: 'whatsapp', label: 'Contact Support' } }, followUp: ['What are the plan limits?', 'Contact support'] },

  // === PAUSE / RESUME / CANCEL ===
  { id: 'pause_subscription', category: 'billing', keywords: ['pause subscription','pause plan','pause karo','subscription rok do','plan pause karo','subscription band karo temporarily','break lena hai'], response: { text: "To pause your subscription:\n1. Go to **Profile** settings.\n2. Find the **Subscription** section.\n3. Click **Pause Subscription**.\n\n**What happens when paused:**\n- Your website goes **offline**\n- All your data is **safely preserved** (products, orders, settings)\n- No charges during pause\n- You can **resume anytime**!", action: { type: 'navigate', label: 'Go to Profile', url: '/dashboard/profile' } }, followUp: ['How to resume?', 'Will I lose my data?'] },
  { id: 'resume_subscription', category: 'billing', keywords: ['resume subscription','resume plan','restart plan','resume karo','plan phir shuru karo','subscription wapas chalu karo','plan restart karo'], response: { text: "To resume your paused subscription:\n1. Go to **Profile** settings.\n2. Find the **Subscription** section.\n3. Click **Resume Subscription**.\n\nYour website will be **back online immediately** with all your data intact! 🎉", action: { type: 'navigate', label: 'Go to Profile', url: '/dashboard/profile' } }, followUp: ['What is my plan status?', 'How much does it cost?'] },
  { id: 'cancel_subscription', category: 'billing', keywords: ['cancel subscription','cancel plan','unsubscribe','subscription cancel karo','plan cancel karo','subscription band karo','stop subscription','plan hatao'], response: { text: "To cancel your subscription:\n1. Go to **Profile** settings.\n2. Find the **Subscription** section.\n3. Click **Cancel Subscription**.\n\n**What happens:**\n- Your plan stays active until the current billing period ends.\n- After that, your website goes offline.\n- Your data is **preserved** — you can resubscribe later.\n\nWe're sad to see you go! If there's an issue, let us help first. 💙", action: { type: 'navigate', label: 'Go to Profile', url: '/dashboard/profile' } }, followUp: ['Can I get a refund?', 'Will I lose my data?'] },

  // === PAYMENT ISSUES ===
  { id: 'payment_failed', category: 'billing', keywords: ['payment failed','payment not working','payment error','cant pay','payment nahi ho raha','payment fail ho gaya','error in payment','payment issue','razorpay error','payment stuck'], response: { text: "If your payment failed, try these steps:\n1. **Check your UPI app** — ensure sufficient balance.\n2. **Try a different UPI** app (Google Pay, PhonePe, Paytm).\n3. **Clear browser cache** and try again.\n4. **Wait 5 minutes** — sometimes banks need time.\n\nIf it still doesn't work, contact us on WhatsApp and we'll help! 📱", action: { type: 'whatsapp', label: 'Get Help on WhatsApp' } }, followUp: ['Contact support', 'Try payment again'] },
  { id: 'payment_not_reflected', category: 'billing', keywords: ['paid but no access','payment done but','money deducted but','charged but no plan','paisa kata lekin','payment ho gaya lekin','subscription nahi mila','payment done subscription not active'], response: { text: "If you've paid but your subscription isn't active:\n1. **Wait 2-3 minutes** — it sometimes takes a moment to sync.\n2. **Refresh the page** (Ctrl+R or pull-to-refresh).\n3. If still not working, your payment may have synced incorrectly.\n\nPlease contact us on WhatsApp with your payment screenshot — we'll fix it immediately! 🔧", action: { type: 'whatsapp', label: 'Report Payment Issue' } }, followUp: ['Contact support'] },

  // === INVOICE / RECEIPT ===
  { id: 'subscription_invoice', category: 'billing', keywords: ['subscription invoice','payment receipt','billing invoice','payment proof','subscription receipt','invoice download','payment invoice','receipt chahiye','invoice dikhao','payment ka proof'], response: { text: "For subscription payment receipts:\n1. Check your **email** — Razorpay sends an automatic receipt.\n2. Check your **UPI app** transaction history.\n\nIf you need an official invoice, contact us on WhatsApp and we'll generate one for you!", action: { type: 'whatsapp', label: 'Request Invoice' } }, followUp: ['Contact support', 'What is my plan?'] },

  // === DATA SAFETY ===
  { id: 'data_after_cancel', category: 'billing', keywords: ['data after cancel','lose data','data safe','data delete','cancel ke baad data','data hata jayega kya','mera data safe hai','data preserved'], response: { text: "**Your data is always safe!** 🔒\n\nEven if you cancel, pause, or let your subscription expire:\n- All products, categories, and images are preserved\n- All order history is preserved\n- All customer data is preserved\n- All website settings are preserved\n\nYou just need to resubscribe to make your website live again!", action: null }, followUp: ['How to resubscribe?', 'How to resume subscription?'] },
];
