// General & FAQ — 65+ intents (EN + Hindi/Hinglish)
export const generalIntents = [
  // === GREETINGS ===
  { id: 'greeting_hi', category: 'general', keywords: ['hi','hello','hey','hii','hiii','helo','namaste','namaskar','kaise ho','how are you','sup','whats up','kya haal hai','greetings'], response: { text: '__GREETING__' }, followUp: ['How do I get started?', 'What can you do?', 'Show me my dashboard'] },
  { id: 'greeting_morning', category: 'general', keywords: ['good morning','morning','subah','suprabhat','gm'], response: { text: '__GREETING__' }, followUp: ['Show my sales', 'Any new orders?', 'What can you help with?'] },
  { id: 'greeting_afternoon', category: 'general', keywords: ['good afternoon','afternoon','dopahar'], response: { text: '__GREETING__' }, followUp: ['Show my sales', 'Any pending orders?'] },
  { id: 'greeting_evening', category: 'general', keywords: ['good evening','evening','shaam','shubh sandhya'], response: { text: '__GREETING__' }, followUp: ['Show today\'s summary', 'Any new orders?'] },
  { id: 'greeting_night', category: 'general', keywords: ['good night','night','raat','shubh ratri'], response: { text: "Good night! 🌙 Rest well — your store is running 24/7 even while you sleep! See you tomorrow. 😊" }, followUp: [] },
  { id: 'thanks', category: 'general', keywords: ['thank you','thanks','thankyou','dhanyavaad','shukriya','ty','thx','thanks a lot','bahut shukriya','thnks','thank u'], response: { text: "You're welcome! 😊 Happy to help! Is there anything else I can assist you with?" }, followUp: ['No, that\'s all', 'Show my dashboard'] },
  { id: 'bye', category: 'general', keywords: ['bye','goodbye','see you','alvida','baad me milte','ok bye','cya','later','talk later','phir milenge'], response: { text: "Bye! 👋 Have a great day! I'm always here when you need me. Good luck with your store! 🚀" }, followUp: [] },
  { id: 'ok', category: 'general', keywords: ['ok','okay','got it','understood','samajh gaya','theek hai','achha','alright','sure','fine','hmm'], response: { text: "Great! 👍 Is there anything else I can help you with?" }, followUp: ['Show my dashboard', 'How to increase sales?'] },

  // === WHAT CAN YOU DO ===
  { id: 'capabilities', category: 'general', keywords: ['what can you do','help me','what do you do','your features','kya kar sakte ho','tumse kya hoga','help kaise milega','what are your capabilities','kya kya kar sakte ho','features kya hain'], response: { text: "I'm **Vista**, your AI store assistant! Here's what I can help with: 🤖\n\n📦 **Products** — Add, edit, manage stock, categories\n📋 **Orders** — View, ship, track, manage\n📊 **Analytics** — Sales, traffic, top products\n🎨 **Website** — Publish, edit, template changes\n💰 **Billing** — Plans, payments, subscriptions\n✍️ **Content** — Write product descriptions, taglines\n🛒 **Offers** — Create discounts, coupons\n👥 **Customers** — View, analyze, retain\n📞 **Support** — Connect to WhatsApp support\n\nJust ask me anything! I understand English and Hindi. 😊", action: null }, followUp: ['How do I get started?', 'Show my sales', 'How to add a product?'] },

  // === ABOUT BIZVISTAR ===
  { id: 'what_is_bizvistar', category: 'general', keywords: ['what is bizvistar','about bizvistar','bizvistar kya hai','tell me about bizvistar','bizvistar ke baare me','who are you','who made this','company info'], response: { text: "**BizVistar** is a SaaS platform that helps Indian shop owners create beautiful **online stores** in minutes! 🇮🇳\n\n**What we offer:**\n- Beautiful, mobile-ready store templates\n- Product & order management\n- Direct UPI payments (zero commission!)\n- Analytics dashboard\n- AI-powered content generation\n\nOur mission: Make e-commerce accessible to every small business in India! 🚀", action: null }, followUp: ['How much does it cost?', 'How to get started?'] },
  { id: 'why_bizvistar', category: 'general', keywords: ['why bizvistar','why should i use','benefit','advantage','competitor','vs shopify','vs woocommerce','kyu use kare','fayda kya hai','shopify se better','compared to others'], response: { text: "**Why choose BizVistar?** 🏆\n\n✅ **Zero commission** — We don't take a cut of your sales\n✅ **Direct payments** — Money goes straight to your UPI\n✅ **₹399/mo** — Cheapest in the market\n✅ **No technical skills needed** — Set up in 5 minutes\n✅ **Beautiful templates** — Professional-looking stores\n✅ **Made for India** — UPI, COD, WhatsApp integration\n✅ **Unlimited products** — No caps on Pro/Growth\n\nMost alternatives charge 2-5% commission + higher monthly fees!", action: null }, followUp: ['How much does it cost?', 'How to get started?'] },

  // === SECURITY & PRIVACY ===
  { id: 'security', category: 'general', keywords: ['is it safe','security','data safe','secure','privacy','safe hai kya','data surakshit hai','mera data safe hai kya','hacking','breach','secure platform'], response: { text: "**Your data is 100% secure!** 🔒\n\n- We use **Supabase** (enterprise-grade infrastructure)\n- All data is **encrypted in transit** (HTTPS)\n- Passwords are **hashed** (never stored in plain text)\n- We **never share** your data with third parties\n- Payments go **directly to your UPI** — we never hold your money\n\nYour trust is our top priority!", action: null }, followUp: ['How does payment work?', 'What happens to my data if I cancel?'] },
  { id: 'privacy_policy', category: 'general', keywords: ['privacy policy','terms','terms of service','terms and conditions','privacy','niyam','sharten'], response: { text: "You can view our privacy policy and terms of service on our website.\n\nIn short: We collect only what's necessary, we never sell your data, and you can delete your account anytime.", action: { type: 'navigate', label: 'Privacy Policy', url: '/privacy' } }, followUp: ['How to delete my account?'] },

  // === MOBILE APP ===
  { id: 'mobile_app', category: 'general', keywords: ['mobile app','android app','ios app','phone app','app download','app kaise download kare','app hai kya','play store','app store','mobile se kaise chalaye'], response: { text: "We don't have a dedicated mobile app yet, but our **website works great on mobile browsers**! 📱\n\n**Quick tip:** Add the website to your home screen:\n1. Open **bizvistar.in** in Chrome\n2. Tap the **⋮** menu → **Add to Home Screen**\n3. It works just like an app!\n\nA native app is on our roadmap! 🚀", action: null }, followUp: ['How to access dashboard on mobile?'] },

  // === CUSTOMER CARE ===
  { id: 'contact_support', category: 'general', keywords: ['contact support','customer care','support','help desk','complaint','talk to human','real person','speak to someone','support team','customer service','customer care number','phone number','call','email support','contact karo','madad chahiye','support se baat karo','human se baat karo','kisi se baat karni hai','complaint hai','shikayat','help chahiye'], response: { text: "You can reach our support team anytime on **WhatsApp**! 📱\n\nOur team typically responds within **30 minutes** during business hours (10 AM - 8 PM IST).\n\nClick below to start a chat! 👇", action: { type: 'whatsapp', label: '📱 Chat on WhatsApp' } }, followUp: [] },
  { id: 'report_bug', category: 'general', keywords: ['bug','error','crash','not working','broken','glitch','problem','issue','kaam nahi kar raha','error aa raha','site crash','bug report','something wrong','page not loading','loading issue','white screen'], response: { text: "I'm sorry you're experiencing an issue! 😔\n\nPlease report this to our team on **WhatsApp** with:\n1. What you were trying to do\n2. What happened instead\n3. A screenshot if possible\n\nWe'll fix it as fast as we can! 🔧", action: { type: 'whatsapp', label: '🐛 Report Bug on WhatsApp' } }, followUp: [] },
  { id: 'feedback', category: 'general', keywords: ['feedback','suggestion','feature request','improvement','idea','suzhav','suggestion hai','feedback dena hai','naya feature chahiye','improvement suggestion'], response: { text: "We love hearing from you! 💙\n\nPlease share your feedback or feature request on **WhatsApp** — every suggestion goes directly to our founding team.\n\nYour ideas help us build a better product for everyone! 🙏", action: { type: 'whatsapp', label: '💡 Share Feedback' } }, followUp: [] },

  // === COMPLIMENTS ===
  { id: 'compliment', category: 'general', keywords: ['great','awesome','amazing','love it','nice','beautiful','wonderful','very good','excellent','bahut accha','maza aa gaya','kamaal hai','best','superb','fantastic'], response: { text: "Thank you so much! 🥰 That means a lot to us! We're working hard every day to make BizVistar even better. Your support keeps us going! 💪" }, followUp: ['Tell your friends about us!', 'How to share my store?'] },
  { id: 'frustration', category: 'general', keywords: ['frustrated','angry','annoyed','irritated','useless','waste','bad','terrible','worst','gussa','pareshan','bekaar','kharab','not happy','disappointed'], response: { text: "I'm really sorry you're feeling this way. 😔 Your frustration is completely valid.\n\nLet me connect you with our support team who can personally help resolve your issue. They're amazing at fixing things! 💙", action: { type: 'whatsapp', label: '🤝 Talk to Our Team' } }, followUp: [] },

  // === MISC ===
  { id: 'no_more_questions', category: 'general', keywords: ['no more questions','thats all','nothing else','no thanks','nahi','bas itna hi','aur kuch nahi','done','all good','sorted'], response: { text: "Alright! Glad I could help! 😊 I'm always here if you need anything. Have a wonderful day! ✨" }, followUp: [] },
  { id: 'what_is_new', category: 'general', keywords: ['whats new','new features','updates','latest features','naya kya hai','kya naya aaya','recent updates','changelog'], response: { text: "**Recent updates:** 🆕\n\n✅ New templates added regularly\n✅ Product variants (size, color)\n✅ Offers & coupons system\n✅ AI-powered content generation\n✅ Improved analytics dashboard\n✅ Low stock notifications\n\nWe ship new features every week! Stay tuned. 🚀", action: null }, followUp: ['What\'s on the roadmap?', 'How to use new features?'] },
  { id: 'roadmap', category: 'general', keywords: ['roadmap','upcoming features','future plans','planned features','aage kya aayega','future me kya hoga','kya kya aane wala hai'], response: { text: "**Coming soon to BizVistar:** 🗺️\n\n🔜 Custom domain support\n🔜 Automated shipping integration\n🔜 Invoice generation\n🔜 Mobile app\n🔜 Custom colors (hex codes)\n🔜 Bulk product upload (CSV)\n🔜 Email marketing integration\n\nStay tuned — exciting stuff is coming! 🚀", action: null }, followUp: ['What\'s available now?', 'How to contact support?'] },
  { id: 'who_is_vista', category: 'general', keywords: ['who are you','your name','kya naam hai','tumhara naam','are you ai','are you bot','bot ho kya','ai ho kya','real ho ya bot'], response: { text: "I'm **Vista**, your AI-powered store assistant! 🤖✨\n\nI'm here to help you with everything — from adding products to checking sales to getting business tips.\n\nI understand both **English** and **Hindi/Hinglish**. Ask me anything!", action: null }, followUp: ['What can you do?', 'Show my dashboard'] },
];
