// Navigation — 40+ intents (EN + Hindi/Hinglish)
export const navigationIntents = [
  { id: 'nav_dashboard', category: 'navigation', keywords: ['go to dashboard','open dashboard','dashboard','home','main page','overview','dashboard dikhao','dashboard kholo','home page','main menu','start page'], response: { text: "Taking you to the **Dashboard** — your command center! 🏠", action: { type: 'navigate', label: 'Go to Dashboard', url: '/dashboard' } }, followUp: ['Show my sales', 'Show pending orders'] },
  { id: 'nav_products', category: 'navigation', keywords: ['go to products','open products','products page','product page','products dikhao','product page kholo','product wala page','mere products','show products'], response: { text: "Opening the **Products** page for you! 📦", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['How to add a product?', 'How many products do I have?'] },
  { id: 'nav_orders', category: 'navigation', keywords: ['go to orders','open orders','orders page','order page','orders dikhao','order page kholo','order wala page','mere orders','show orders'], response: { text: "Opening the **Orders** page! 📋", action: { type: 'navigate', label: 'Go to Orders', url: '/dashboard/orders' } }, followUp: ['Show pending orders', 'How to manage orders?'] },
  { id: 'nav_analytics', category: 'navigation', keywords: ['go to analytics','open analytics','analytics page','stats','statistics','analytics dikhao','analytics kholo','stats page','data page','charts page'], response: { text: "Opening **Analytics** — see how your store is performing! 📊", action: { type: 'navigate', label: 'Go to Analytics', url: '/dashboard/analytics' } }, followUp: ['What are my sales?', 'Show traffic data'] },
  { id: 'nav_website', category: 'navigation', keywords: ['go to website','open editor','website editor','edit website','editor page','website page','editor kholo','website edit karo','design page','website dikhao','open website'], response: { text: "Opening the **Website Editor** — time to customize! 🎨", action: { type: 'navigate', label: 'Go to Editor', url: '/dashboard/website' } }, followUp: ['How to publish?', 'How to change template?'] },
  { id: 'nav_profile', category: 'navigation', keywords: ['go to profile','open profile','profile page','settings','account settings','profile dikhao','profile kholo','settings page','my account','account page'], response: { text: "Opening your **Profile** settings! ⚙️", action: { type: 'navigate', label: 'Go to Profile', url: '/dashboard/profile' } }, followUp: ['How to update my info?', 'How to change password?'] },
  { id: 'nav_pricing', category: 'navigation', keywords: ['go to pricing','pricing page','plans','subscription page','pricing dikhao','plan page kholo','plans dekhna hai','pricing page dikhao'], response: { text: "Opening the **Pricing** page — check out our plans! 💰", action: { type: 'navigate', label: 'View Pricing', url: '/pricing' } }, followUp: ['What plan should I choose?', 'How much does it cost?'] },
  { id: 'nav_apps', category: 'navigation', keywords: ['go to apps','apps page','integrations','apps dikhao','apps kholo','add ons','extensions','plugins','apps wala page'], response: { text: "Opening the **Apps** page — explore integrations! 🔌", action: { type: 'navigate', label: 'Go to Apps', url: '/dashboard/apps' } }, followUp: ['What apps are available?', 'How to integrate?'] },

  // === WHERE IS ===
  { id: 'where_products', category: 'navigation', keywords: ['where is products','where are my products','products kaha hai','product page kaha hai','where can i see products','product section kaha hai'], response: { text: "Your products are on the **Products** page! Click the link below to go there. 📦", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['How to add a product?'] },
  { id: 'where_orders', category: 'navigation', keywords: ['where is orders','where are my orders','orders kaha hai','order page kaha hai','where to see orders','order section kaha hai'], response: { text: "Your orders are on the **Orders** page! Click below to view them. 📋", action: { type: 'navigate', label: 'Go to Orders', url: '/dashboard/orders' } }, followUp: ['Show pending orders'] },
  { id: 'where_analytics', category: 'navigation', keywords: ['where is analytics','where to see stats','analytics kaha hai','stats kaha hain','data kahan dekhein','where are analytics'], response: { text: "Your analytics are on the **Analytics** page and the main **Dashboard**! 📊", action: { type: 'navigate', label: 'Go to Analytics', url: '/dashboard/analytics' } }, followUp: ['Show my sales'] },
  { id: 'where_editor', category: 'navigation', keywords: ['where is editor','where to edit website','editor kaha hai','website editor kaha hai','website kaise edit kare','design kaha se kare'], response: { text: "The website editor is on the **Website** page! Click below to open it. 🎨", action: { type: 'navigate', label: 'Go to Editor', url: '/dashboard/website' } }, followUp: ['How to publish?'] },
  { id: 'where_settings', category: 'navigation', keywords: ['where is settings','where are settings','settings kaha hai','profile kaha hai','options kahan hain','settings page kahan hai'], response: { text: "Settings are in your **Profile** page — accessible from the sidebar! ⚙️", action: { type: 'navigate', label: 'Go to Profile', url: '/dashboard/profile' } }, followUp: ['How to update profile?'] },

  // === SHOW ME ===
  { id: 'show_dashboard', category: 'navigation', keywords: ['show me dashboard','show dashboard','dashboard batao','show me overview','overview dikhao','show me home'], response: { text: "Here's your **Dashboard** — your store at a glance! 🏠", action: { type: 'navigate', label: 'Go to Dashboard', url: '/dashboard' } }, followUp: ['What are my sales?'] },
  { id: 'show_products', category: 'navigation', keywords: ['show me products','show products','products batao','show my products','mere product dikhao','product list dikhao'], response: { text: "Here are your **Products**! 📦", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['How many products do I have?'] },
  { id: 'show_orders', category: 'navigation', keywords: ['show me orders','show orders','orders batao','show my orders','mere order dikhao','order list dikhao'], response: { text: "Here are your **Orders**! 📋", action: { type: 'navigate', label: 'Go to Orders', url: '/dashboard/orders' } }, followUp: ['Show pending orders'] },
];
