// Onboarding — 30+ intents (EN + Hindi/Hinglish)
export const onboardingIntents = [
  { id: 'getting_started', category: 'onboarding', keywords: ['getting started','how to start','where to begin','setup guide','start kaise kare','shuru kaise kare','kaise shuru kare','pehla kadam','first step','new here','i am new','main naya hoon','just joined','abhi join kiya'], response: { text: "Welcome! 🎉 Here's your **Quick Start Guide:**\n\n**Step 1:** Set up your business info (name, logo, WhatsApp)\n**Step 2:** Add your first products (name, price, photo)\n**Step 3:** Set up payments (UPI ID)\n**Step 4:** Choose a template for your website\n**Step 5:** Publish and share your store link! 🚀\n\nNeed help with any step? Just ask!", action: { type: 'navigate', label: 'Go to Dashboard', url: '/dashboard' } }, followUp: ['How to add my first product?', 'How to set up payments?', 'How to choose a template?'] },
  { id: 'first_product', category: 'onboarding', keywords: ['first product','pehla product','add my first product','pehla item','how to start selling','selling start karo','pehla product kaise daale','first item add'], response: { text: "To add your first product:\n1. Go to **Products** page.\n2. Click **Add Product**.\n3. Fill in:\n   - **Name** — What you're selling\n   - **Price** — How much it costs\n   - **Image** — A good photo of the product\n   - **Description** — Brief details\n4. Click **Save**.\n\nCongratulations on your first product! 🎉", action: { type: 'navigate', label: 'Add First Product', url: '/dashboard/products' } }, followUp: ['How to add more products?', 'How to set up my website?'] },
  { id: 'first_website', category: 'onboarding', keywords: ['first website','setup website','create website','make website','website banana hai','pehli website','website kaise banaye','store banao','online store banana hai'], response: { text: "Your website is already being set up! 🏗️\n\n1. Add your **business info** and **logo** in Profile.\n2. Add some **products**.\n3. Go to **Website/Editor** to customize your template.\n4. Click **Publish** when ready!\n\nYour store will be live at: **yourname.bizvistar.in**", action: { type: 'navigate', label: 'Go to Editor', url: '/dashboard/website' } }, followUp: ['How to choose a template?', 'How to add products?'] },
  { id: 'setup_checklist', category: 'onboarding', keywords: ['setup checklist','what to do next','checklist','setup steps','kya kya karna hai','steps kya hain','checklist dikhao','todo list'], response: { text: "**Your Setup Checklist:** ✅\n\n☐ Add business name & logo\n☐ Set WhatsApp number\n☐ Add at least 3 products\n☐ Set up UPI payment\n☐ Choose a template\n☐ Customize your website\n☐ Publish your store\n☐ Share your store link\n\nHow far along are you? I can help with any step!", action: null }, followUp: ['How to add products?', 'How to set up UPI?', 'How to publish?'] },
  { id: 'share_store', category: 'onboarding', keywords: ['share store','share link','share my website','store share karo','link share karo','store ka link bhejo','how to share','link kaise share kare','promote store','store promote karo'], response: { text: "To share your store:\n1. Your store link is: **yourname.bizvistar.in**\n2. Share it on:\n   - **WhatsApp** — Send to contacts & update status\n   - **Instagram** — Add to bio link\n   - **Facebook** — Share as a post\n   - **SMS** — Text to customers\n\n**Pro tip:** Add your store link to your Instagram bio for maximum visibility! 📱", action: null }, followUp: ['What is my store link?', 'How to get more customers?'] },
  { id: 'first_customer', category: 'onboarding', keywords: ['first customer','get customers','find customers','customer kaise laaye','pehla customer','customer kaise milega','first order','pehla order kaise aaye'], response: { text: "**Getting your first customer:** 🎯\n\n1. **WhatsApp blast** — Share your store link with friends & family\n2. **WhatsApp Status** — Post product photos daily\n3. **Instagram** — Post reels showing your products\n4. **Facebook Groups** — Share in relevant local groups\n5. **Word of mouth** — Tell everyone about your store!\n6. **Offer a launch discount** — \"10% off for first 50 customers!\"\n\nThe first customer is the hardest — after that it gets easier! 💪", action: null }, followUp: ['How to create a discount offer?', 'How to share my store?'] },
  { id: 'first_sale', category: 'onboarding', keywords: ['first sale','first order','pehli sale','pehla order','how to get first sale','sale kaise ho','first revenue'], response: { text: "**Tips for your first sale:**\n\n1. ✅ Make sure your store is **published**\n2. 📸 Add **great product photos**\n3. 💰 Set **competitive prices**\n4. 📱 Share link on **WhatsApp + Instagram**\n5. 🏷️ Create a **launch offer** (e.g., 10% off)\n6. 🗣️ Ask friends to **share your store**\n\nMost sellers get their first order within the first week of sharing! 🚀", action: null }, followUp: ['How to create an offer?', 'How to share my store?'] },
  { id: 'business_tips', category: 'onboarding', keywords: ['business tips','selling tips','ecommerce tips','online selling tips','business advice','dukaan chalane ke tips','business kaise kare','tips for selling online'], response: { text: "**Top Tips for Online Selling:** 📈\n\n1. **Quality photos** — #1 factor in online sales\n2. **Regular updates** — Add new products regularly\n3. **Respond fast** — Quick replies build trust\n4. **Use WhatsApp** — It's your best marketing tool\n5. **Create offers** — Everyone loves a deal\n6. **Ask for reviews** — Social proof sells\n7. **Track analytics** — Know what's working\n8. **Be consistent** — Share daily, not weekly\n\nYou're building something great! Keep going! 💪", action: null }, followUp: ['How to increase sales?', 'How to get more traffic?'] },
];
