// Orders Domain — 55+ intents (EN + Hindi/Hinglish)
export const orderIntents = [
  // === VIEW ORDERS ===
  { id: 'view_orders', category: 'orders', keywords: ['view orders','see orders','my orders','order list','all orders','orders dekhna hai','saare order dikhao','order list dikhao','orders kaha hain','meri orders','show orders','open orders'], response: { text: "To view all your orders:\n1. Go to **Orders** page from the sidebar.\n2. You'll see all orders sorted by newest first.\n3. Each order shows customer name, amount, status, and date.\n\nYou can search and filter orders from there!", action: { type: 'navigate', label: 'Go to Orders', url: '/dashboard/orders' } }, followUp: ['How many pending orders do I have?', 'How to manage an order?', 'How to ship an order?'] },
  { id: 'pending_orders', category: 'orders', keywords: ['pending orders','unshipped orders','new orders','pending order kitne hain','kitne order pending hain','new order aaye','nayi orders','orders not shipped','unprocessed orders','awaiting orders'], response: { text: "Let me check your pending orders...", action: { type: 'data_query', handler: 'getChatOrderData' } }, followUp: ['How to ship an order?', 'How to manage orders?'] },
  { id: 'order_count', category: 'orders', keywords: ['how many orders','total orders','order count','kitne order aaye','total order kitne hain','order ki sankhya','number of orders','aaj kitne order aaye'], response: { text: "Let me check your order numbers...", action: { type: 'data_query', handler: 'getChatOrderData' } }, followUp: ['Show pending orders', 'What are my total sales?'] },
  { id: 'todays_orders', category: 'orders', keywords: ['today orders','orders today','aaj ke order','aaj kitne order','today ka order','new orders today','latest orders'], response: { text: "Let me check today's orders for you...", action: { type: 'data_query', handler: 'getChatOrderData' } }, followUp: ['What are my sales today?', 'Show pending orders'] },

  // === MANAGE ORDER ===
  { id: 'manage_order', category: 'orders', keywords: ['manage order','handle order','process order','order manage karo','order kaise manage kare','order handle karo','order process karo','deal with order','update order'], response: { text: "To manage an order:\n1. Go to **Orders** page.\n2. Find the order you want to manage.\n3. Click the **Manage** button on the right.\n4. A popup will appear where you can:\n   - Update order status (Pending → Paid → Shipped → Delivered)\n   - Add tracking/logistics details\n   - View customer info", action: { type: 'navigate', label: 'Go to Orders', url: '/dashboard/orders' } }, followUp: ['How to mark order as shipped?', 'How to add tracking number?'] },

  // === ORDER STATUS ===
  { id: 'mark_paid', category: 'orders', keywords: ['mark paid','mark as paid','order paid','payment received','paid mark karo','paid karo','payment aa gaya','order ka payment hua'], response: { text: "To mark an order as paid:\n1. Go to **Orders** → click **Manage** on the order.\n2. Change status to **Paid**.\n3. Save.\n\nThis confirms you've received the payment for this order.", action: { type: 'navigate', label: 'Go to Orders', url: '/dashboard/orders' } }, followUp: ['How to ship this order?', 'How to mark as delivered?'] },
  { id: 'mark_shipped', category: 'orders', keywords: ['mark shipped','ship order','order shipped','mark as shipped','shipping karo','order ship karo','shipped mark karo','order bhejo','order dispatch karo','dispatch order'], response: { text: "To mark an order as shipped:\n1. Go to **Orders** → click **Manage** on the order.\n2. Change status to **Shipped**.\n3. Optionally add tracking details (courier name, tracking number).\n4. Save.\n\n**Tip:** Adding tracking info helps your customers track their delivery!", action: { type: 'navigate', label: 'Go to Orders', url: '/dashboard/orders' } }, followUp: ['How to add tracking number?', 'How to mark as delivered?'] },
  { id: 'mark_delivered', category: 'orders', keywords: ['mark delivered','order delivered','delivery complete','delivered mark karo','deliver ho gaya','order pahunch gaya','delivery done','order complete'], response: { text: "To mark an order as delivered:\n1. Go to **Orders** → click **Manage** on the order.\n2. Change status to **Delivered**.\n3. Save.\n\nThis completes the order cycle! 🎉", action: { type: 'navigate', label: 'Go to Orders', url: '/dashboard/orders' } }, followUp: ['Show completed orders', 'What are my total sales?'] },

  // === TRACKING & SHIPPING ===
  { id: 'add_tracking', category: 'orders', keywords: ['add tracking','tracking number','tracking details','add courier','courier details','tracking daalo','tracking number add karo','courier information','tracking kaise daale','logistics add karo','awb number'], response: { text: "To add tracking/logistics details:\n1. Go to **Orders** → click **Manage** on the order.\n2. In the popup, look for **Logistics** section.\n3. Enter:\n   - **Courier/Provider** name (e.g., Delhivery, BlueDart)\n   - **Tracking Number** (AWB number)\n4. Save.\n\nThe order will automatically be marked as **Shipped**.", action: { type: 'navigate', label: 'Go to Orders', url: '/dashboard/orders' } }, followUp: ['How to ship an order?', 'Which couriers do you support?'] },
  { id: 'shipping_integration', category: 'orders', keywords: ['shipping integration','auto shipping','automated shipping','shipping partner','shipping service','automatic shipping','shipping automation','delhivery integration','shiprocket'], response: { text: "We are currently in **Beta** and do not support automated shipping integrations yet (like Shiprocket or Delhivery API).\n\n**What you can do now:**\n1. Ship via your local courier or any delivery service.\n2. Add the tracking number manually in the order.\n3. Mark order as **Shipped**.\n\nAutomated shipping is on our roadmap! 🚀", action: null }, followUp: ['How to add tracking number?', 'How to mark order as shipped?'] },
  { id: 'shipping_cost', category: 'orders', keywords: ['shipping cost','delivery charge','shipping charge','delivery fee','shipping kitna lagega','delivery charge kaise set kare','shipping fee set karo','delivery cost'], response: { text: "To set delivery charges:\n1. Go to **Profile** settings.\n2. Find the **Delivery Settings** section.\n3. Choose:\n   - **Fixed delivery charge** (e.g., ₹50 per order)\n   - **Free above threshold** (e.g., free delivery above ₹500)\n4. Save.\n\nCustomers will see this charge at checkout.", action: { type: 'navigate', label: 'Go to Profile', url: '/dashboard/profile' } }, followUp: ['How to set free delivery?', 'How to update my profile?'] },

  // === CANCEL ORDER ===
  { id: 'cancel_order', category: 'orders', keywords: ['cancel order','order cancel','cancel karo','order cancel karna hai','order raddkaro','order band karo','order reject','reject order','decline order'], response: { text: "To cancel an order:\n1. Go to **Orders** → click **Manage** on the order.\n2. Change status to **Canceled**.\n3. Save.\n\n⚠️ **Note:** Stock for canceled orders is **not** automatically restored. You may need to manually update product stock.", action: { type: 'navigate', label: 'Go to Orders', url: '/dashboard/orders' } }, followUp: ['How to update stock after cancellation?', 'How to refund?'] },
  { id: 'refund_order', category: 'orders', keywords: ['refund','refund order','money back','return order','refund karo','paisa wapas karo','return policy','refund policy','paisa vapas','refund kaise hoga'], response: { text: "Since payments are processed **directly between you and your customer** (via UPI), refunds need to be handled manually.\n\n**Steps:**\n1. Cancel the order in your dashboard.\n2. Refund the customer directly via UPI/bank transfer.\n3. Inform the customer via WhatsApp.\n\nIf you need help, contact our team on WhatsApp! 📱", action: { type: 'whatsapp', label: 'Contact Support' } }, followUp: ['How to cancel an order?', 'Contact customer care'] },

  // === ORDER SOURCES ===
  { id: 'pos_order', category: 'orders', keywords: ['pos order','manual order','walk-in order','offline order','in-store order','pos se order','manual order kaise kare','walk in customer','counter sale','point of sale'], response: { text: "To add a **manual/POS order** (for walk-in customers):\n1. Go to your store's checkout page.\n2. Add products to cart as a customer would.\n3. Fill in customer details.\n4. Check **\"Manual Order\"** option.\n5. Submit the order.\n\nIt will appear in your Orders dashboard marked as **POS** order.", action: null }, followUp: ['How to view all orders?', 'How to manage orders?'] },
  { id: 'order_source', category: 'orders', keywords: ['order source','where did order come from','website order vs pos','order kahan se aaya','order type','order channel'], response: { text: "Every order shows its **source**:\n- **Website** — Customer ordered from your online store\n- **POS** — You added it manually (walk-in/phone order)\n\nYou can see this in the Orders page!", action: { type: 'navigate', label: 'Go to Orders', url: '/dashboard/orders' } }, followUp: ['How to add a POS order?', 'Show today\'s orders'] },

  // === EXPORT ===
  { id: 'export_orders', category: 'orders', keywords: ['export orders','download orders','orders csv','orders excel','order data download','orders export karo','order ka data download','order report','order data nikalo'], response: { text: "To export your order data:\n1. Go to the **Dashboard** page.\n2. Click the **Export CSV** button in the top right.\n3. Select the data you want to export.\n4. Download the CSV file.\n\nYou can open the CSV in Excel or Google Sheets!", action: { type: 'navigate', label: 'Go to Dashboard', url: '/dashboard' } }, followUp: ['How to view analytics?', 'What are my sales this month?'] },

  // === INVOICES ===
  { id: 'invoice', category: 'orders', keywords: ['invoice','print invoice','order invoice','bill','receipt','order receipt','invoice print karo','bill nikalo','receipt dikhao','invoice kaise banaye','generate invoice'], response: { text: "Currently, **automatic invoice generation** is not available yet. It's coming soon! 🚀\n\n**What you can do now:**\n1. Use the **Export CSV** feature to get order details.\n2. Use a free invoice generator like **Invoice Ninja** or **Zoho Invoice**.\n3. Copy order details from the **Manage** popup.\n\nInvoice generation is on our roadmap!", action: null }, followUp: ['How to export orders?', 'How to manage an order?'] },

  // === CUSTOMER FROM ORDER ===
  { id: 'order_customer_details', category: 'orders', keywords: ['customer details','order customer info','who ordered','customer address','shipping address','customer ka address','kisne order kiya','customer info dekhna hai','buyer details'], response: { text: "To view customer details for an order:\n1. Go to **Orders** → click **Manage** on the order.\n2. The popup shows:\n   - Customer **name** and **email**\n   - **Shipping address**\n   - **Phone number** (if provided)\n\nYou can also see all customers in the customer list.", action: { type: 'navigate', label: 'Go to Orders', url: '/dashboard/orders' } }, followUp: ['How many customers do I have?', 'How to contact a customer?'] },

  // === ORDER SEARCH ===
  { id: 'search_orders', category: 'orders', keywords: ['search order','find order','order search','order dhundho','order kaise dhundhe','find specific order','look up order','order id search'], response: { text: "To search for a specific order:\n1. Go to the **Dashboard** page.\n2. Use the **Search bar** at the top.\n3. You can search by:\n   - Order ID\n   - Customer name\n   - Order amount\n   - Order status\n\nResults update as you type!", action: { type: 'navigate', label: 'Go to Dashboard', url: '/dashboard' } }, followUp: ['Show pending orders', 'How to manage an order?'] },
  { id: 'filter_orders', category: 'orders', keywords: ['filter orders','orders by date','orders by status','order filter','specific date orders','date wise orders','status wise orders','order ko filter karo'], response: { text: "To filter orders:\n1. Go to **Dashboard** page.\n2. Click the **Filter** button (funnel icon).\n3. Select time period:\n   - Last 7 days\n   - Last 30 days\n   - Last 3 months\n\nYou can also search to narrow results further.", action: { type: 'navigate', label: 'Go to Dashboard', url: '/dashboard' } }, followUp: ['Export order data', 'Show today\'s orders'] },
];
