// Products Domain — 65 intents (EN + Hindi/Hinglish)
export const productIntents = [
  // === ADD PRODUCT ===
  { id: 'add_product', category: 'products', keywords: ['add product','create product','new product','upload item','sell new item','how to add product','add inventory','naya product add karo','product kaise add kare','naya item daalo','product banana hai','add new item','list a product','list new product','product upload','i want to add product','product daalna hai'], response: { text: "To add a new product:\n1. Go to **Products** page.\n2. Click the **Add Product** button (top right).\n3. Fill in name, price, description, and upload an image.\n4. Set stock quantity (or leave blank for unlimited).\n5. Click **Save**.\n\nThat's it! Your product will be live on your store. 🎉", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['How to add product images?', 'How to set product categories?', 'How to add variants?'] },
  { id: 'add_product_bulk', category: 'products', keywords: ['add multiple products','bulk add','add many products','bulk upload','upload many items','bahut saare product add karne hain','ek saath product daalo','multiple items add'], response: { text: "Currently, you can add products one at a time from the **Products** page. Bulk upload via CSV is not available yet, but it's on our roadmap!\n\n**Tip:** You can quickly add products from the onboarding wizard too.", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['How to add a product?', 'How to manage categories?'] },

  // === EDIT PRODUCT ===
  { id: 'edit_product', category: 'products', keywords: ['edit product','change product','update product','modify item','modify product','how to edit product','edit price','edit name','product edit karo','product change karna hai','product update kaise kare','product modify karo','product details change','i want to edit product','change product details'], response: { text: "To edit a product:\n1. Go to **Products** page.\n2. Find the product you want to change.\n3. Click the **⋯** (three dots) button next to it.\n4. Select **Edit** from the dropdown.\n5. Update the details and click **Save**.", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['How to change product price?', 'How to update stock?', 'How to change product image?'] },
  { id: 'edit_product_price', category: 'products', keywords: ['change price','update price','edit price','modify price','price change karo','price update karo','product ki price badle','daam badlo','rate change karna hai','price kaise badle'], response: { text: "To change a product's price:\n1. Go to **Products** → click **⋯** next to the product → **Edit**.\n2. Update the **Price** field.\n3. Click **Save**.\n\nThe new price will reflect on your live store immediately after saving!", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['How to edit product description?', 'How to update stock?'] },
  { id: 'edit_product_name', category: 'products', keywords: ['change product name','update product name','rename product','product ka naam badle','naam change karo','product rename karo'], response: { text: "To rename a product:\n1. Go to **Products** → click **⋯** → **Edit**.\n2. Change the **Name** field.\n3. Click **Save**.\n\nDone! The updated name will show on your store.", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['How to edit product price?', 'How to change product image?'] },
  { id: 'edit_product_description', category: 'products', keywords: ['change description','update description','edit description','product description change','description update karo','product ki description badle','description likhna hai'], response: { text: "To update a product description:\n1. Go to **Products** → click **⋯** → **Edit**.\n2. Update the **Description** field.\n3. Click **Save**.\n\n**Tip:** Keep descriptions short and highlight key features — customers love bullet points!", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['Write a product description for me', 'How to add product images?'] },

  // === DELETE PRODUCT ===
  { id: 'delete_product', category: 'products', keywords: ['delete product','remove product','trash item','remove item','how to delete product','product delete karo','product hatao','product remove karo','product kaise delete kare','item delete karna hai','product mitao'], response: { text: "To delete a product:\n1. Go to **Products** page.\n2. Click the **⋯** (three dots) next to the product.\n3. Select **Delete**.\n\n⚠️ **Warning:** This action cannot be undone. The product will be permanently removed from your store.", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['How to edit a product instead?', 'How to hide a product without deleting?'] },

  // === STOCK MANAGEMENT ===
  { id: 'check_stock', category: 'products', keywords: ['check stock','view stock','stock status','how much stock','stock kitna hai','stock check karo','stock dekhna hai','inventory check','stock level','remaining stock','stock kaise dekhe'], response: { text: "To check your product stock:\n1. Go to **Products** page.\n2. Each product shows its stock status:\n   - **Active** — In stock\n   - **Low Stock** — Less than 10 remaining\n   - **Out of Stock** — 0 remaining\n   - **Unlimited** — No stock limit set\n\nYou can also ask me: **\"Show low stock products\"** and I'll check for you!", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['Show low stock products', 'How to update stock?', 'How to set unlimited stock?'] },
  { id: 'update_stock', category: 'products', keywords: ['update stock','change stock','set stock','stock update karo','stock badhao','stock kam karo','stock change karna hai','stock set karo','inventory update','restock','stock badalna hai'], response: { text: "To update product stock:\n1. Go to **Products** → click **⋯** → **Edit**.\n2. Update the **Stock** field with the new quantity.\n3. Click **Save**.\n\n**Tip:** Set stock to **-1** or leave blank for **unlimited stock** (good for digital products or made-to-order items).", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['How to set unlimited stock?', 'Show out of stock products'] },
  { id: 'unlimited_stock', category: 'products', keywords: ['unlimited stock','no stock limit','infinite stock','remove stock limit','unlimited inventory','stock limit hatao','unlimited stock kaise kare','stock limit nahi chahiye'], response: { text: "To set unlimited stock for a product:\n1. Go to **Products** → click **⋯** → **Edit**.\n2. Leave the **Stock** field empty, or set it to **Unlimited**.\n3. Click **Save**.\n\nThe product will never show \"Out of Stock\" to your customers.", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['How to check stock levels?', 'How to add a product?'] },
  { id: 'out_of_stock', category: 'products', keywords: ['out of stock','product out of stock','no stock left','stock khatam','stock zero','product stock empty','sold out','stock finish ho gaya','koi stock nahi bacha'], response: { text: "If a product is out of stock:\n- It will show **\"Out of Stock\"** status on your Products page.\n- Customers **can still see it** on your store but cannot buy it.\n\nTo restock: Go to **Products** → **Edit** the product → Update the **Stock** quantity → **Save**.", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['Show out of stock products', 'How to update stock?', 'How to set unlimited stock?'] },
  { id: 'low_stock_alert', category: 'products', keywords: ['low stock alert','stock alert','stock warning','low stock notification','stock kam hone par alert','stock alert kaise set kare','low stock warning'], response: { text: "We automatically send you **low stock alerts** when any product drops below 5 units! 🔔\n\nYou'll see these in your **Notifications** bell icon on the dashboard. Products with less than 10 units show as **\"Low Stock\"** in your products list.", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['Show low stock products', 'How to update stock?'] },

  // === CATEGORIES ===
  { id: 'add_category', category: 'products', keywords: ['add category','create category','new category','make category','category add karo','category banana hai','category kaise banaye','naya category banao','product category add'], response: { text: "To add a product category:\n1. Go to **Products** page.\n2. Click the **Categories** tab or section.\n3. Click **Add Category**.\n4. Enter a name and save.\n\nThen you can assign products to this category while adding or editing them.", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['How to assign a product to a category?', 'How to edit a category?'] },
  { id: 'edit_category', category: 'products', keywords: ['edit category','change category name','update category','rename category','category edit karo','category ka naam badle','category update karo'], response: { text: "To edit a category:\n1. Go to **Products** → **Categories** tab.\n2. Click the **edit** icon next to the category.\n3. Update the name and save.", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['How to delete a category?', 'How to add a category?'] },
  { id: 'delete_category', category: 'products', keywords: ['delete category','remove category','category delete karo','category hatao','category remove karo','category kaise delete kare'], response: { text: "To delete a category:\n1. Go to **Products** → **Categories** tab.\n2. Click the **delete** icon next to the category.\n\n⚠️ Products in this category will become **Uncategorized** — they won't be deleted.", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['How to add a new category?', 'How to reassign products?'] },
  { id: 'assign_category', category: 'products', keywords: ['assign category','set category','move product to category','change product category','product ko category me daalo','product ki category badle','categorize product','product category set karo'], response: { text: "To assign a product to a category:\n1. Go to **Products** → **Edit** the product.\n2. Select the desired **Category** from the dropdown.\n3. Click **Save**.\n\nYou can also bulk-assign products using the category manager!", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['How to create a new category?', 'How to bulk assign categories?'] },

  // === VARIANTS ===
  { id: 'add_variants', category: 'products', keywords: ['add variant','product variant','add size','add color','variant add karo','size add karo','color add karo','variant kaise add kare','product me size daalo','product me color daalo','variant banana hai'], response: { text: "To add variants (size, color, etc.) to a product:\n1. Go to **Products** → **Edit** the product.\n2. Scroll down to the **Variants** section.\n3. Click **Add Variant**.\n4. Enter variant name (e.g., \"Size\") and options (e.g., S, M, L, XL).\n5. Click **Save**.\n\nCustomers will see a dropdown to select variants when ordering!", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['How to edit variants?', 'How to delete a variant?'] },
  { id: 'edit_variants', category: 'products', keywords: ['edit variant','change variant','update variant','modify variant','variant edit karo','variant badle','variant update karo'], response: { text: "To edit product variants:\n1. Go to **Products** → **Edit** the product.\n2. In the **Variants** section, modify the variant names or options.\n3. Click **Save**.", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['How to add more variants?', 'How to delete a variant?'] },
  { id: 'delete_variants', category: 'products', keywords: ['delete variant','remove variant','variant delete karo','variant hatao','variant remove karo'], response: { text: "To remove a variant:\n1. Go to **Products** → **Edit** the product.\n2. In the **Variants** section, click the **×** next to the variant to remove it.\n3. Click **Save**.", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['How to add variants?', 'How to edit a product?'] },

  // === IMAGES ===
  { id: 'add_product_image', category: 'products', keywords: ['add product image','upload product image','product photo','product image upload','change product image','product ki photo daalo','product image kaise lagaye','photo upload karo','image add karo','product picture'], response: { text: "To add/change a product image:\n1. Go to **Products** → **Edit** the product.\n2. Click on the **image area** to upload a new photo.\n3. Select an image from your device.\n4. Click **Save**.\n\n**Tips:**\n- Use clear, well-lit photos.\n- Square images (1:1 ratio) work best.\n- Max file size: 10MB.", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['How to add additional images?', 'What image size works best?'] },
  { id: 'additional_images', category: 'products', keywords: ['additional images','more images','multiple images','extra photos','additional photos','aur photos daalo','multiple photos upload','zyada images add karo','gallery images'], response: { text: "To add multiple images to a product:\n1. Go to **Products** → **Edit** the product.\n2. Below the main image, you'll see an **Additional Images** section.\n3. Click to upload more images.\n4. Click **Save**.\n\nCustomers can swipe through all images on your store page!", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['How to change the main image?', 'What image format is best?'] },
  { id: 'image_requirements', category: 'products', keywords: ['image size','image format','photo requirements','image requirements','photo size','image quality','image specs','photo format','kitni badi image ho','photo ki size'], response: { text: "**Product Image Requirements:**\n- **Format:** JPG, PNG, or WebP\n- **Max size:** 10MB per image\n- **Recommended:** Square (1:1 ratio), at least 800×800px\n- **Tips:** Use natural lighting, clean background, and show the product clearly.\n\nImages are automatically optimized for fast loading on your store.", action: null }, followUp: ['How to upload a product image?', 'How to add additional images?'] },

  // === PRODUCT DISPLAY ===
  { id: 'product_display_settings', category: 'products', keywords: ['product display','sort order','grid columns','products per page','display settings','product layout','product grid','shop page layout','product display settings','product arrangement'], response: { text: "To change product display settings:\n1. Go to **Website** editor.\n2. Look for **Product Display Settings** in the sidebar.\n3. You can change:\n   - **Sort Order** (newest, price low-high, etc.)\n   - **Grid Columns** (2, 3, or 4 columns)\n   - **Products Per Page** (12, 24, 48)\n\nThese settings apply to your shop page.", action: { type: 'navigate', label: 'Go to Editor', url: '/dashboard/website' } }, followUp: ['How to change my template?', 'How to publish my website?'] },

  // === SEARCH & FILTER ===
  { id: 'search_products', category: 'products', keywords: ['search product','find product','filter products','product search','product dhundho','product kaise dhundhe','search kaise kare','product filter'], response: { text: "To search or filter products:\n1. Go to **Products** page.\n2. Use the **Search bar** at the top to find products by name.\n3. Use the **Category filter** to show products from a specific category.\n4. Use the **Stock Status filter** to show only Low Stock, Out of Stock, etc.", action: { type: 'navigate', label: 'Go to Products', url: '/dashboard/products' } }, followUp: ['How many products do I have?', 'Show low stock products'] },
  { id: 'product_count', category: 'products', keywords: ['how many products','total products','product count','kitne product hain','product ki sankhya','mere kitne product hain','total items','number of products'], response: { text: "I can check that for you! Let me look up your product count...", action: { type: 'data_query', handler: 'getChatProductData' } }, followUp: ['Show low stock products', 'How to add a product?'] },
  { id: 'product_limit', category: 'products', keywords: ['product limit','max products','how many products can i add','product limit kitna hai','kitne product add kar sakte hain','maximum products','product quota'], response: { text: "Product limits depend on your plan:\n- **Starter Plan:** Up to 25 products\n- **Pro/Growth Plan:** Unlimited products! 🎉\n\nYou can check your current plan in **Profile** settings.", action: { type: 'navigate', label: 'Check Plan', url: '/dashboard/profile' } }, followUp: ['What is my current plan?', 'How to upgrade my plan?'] },
];
