// Profile & Settings — 35+ intents (EN + Hindi/Hinglish)
export const profileIntents = [
  { id: 'update_profile', category: 'profile', keywords: ['update profile','edit profile','change profile','profile settings','profile update karo','profile edit karo','profile change karo','settings change','apni details badle'], response: { text: "To update your profile:\n1. Go to **Profile** page from the sidebar.\n2. Update your details:\n   - Business name\n   - Owner name\n   - WhatsApp number\n   - UPI ID\n   - Delivery settings\n   - Billing address\n3. Click **Save**.", action: { type: 'navigate', label: 'Go to Profile', url: '/dashboard/profile' } }, followUp: ['How to change business name?', 'How to update UPI?'] },
  { id: 'change_business_name', category: 'profile', keywords: ['change business name','update store name','rename store','business name change','store ka naam badle','business name update karo','shop name change','dukaan ka naam badle'], response: { text: "To change your business/store name:\n1. Go to **Profile** page.\n2. Update the **Business Name** field.\n3. Click **Save**.\n\nThis updates your store name everywhere — header, footer, and all pages!", action: { type: 'navigate', label: 'Go to Profile', url: '/dashboard/profile' } }, followUp: ['How to change logo?', 'How to update website?'] },
  { id: 'update_whatsapp', category: 'profile', keywords: ['update whatsapp','change whatsapp','whatsapp number','add whatsapp','whatsapp number badle','whatsapp change karo','whatsapp update karo','new whatsapp number','whatsapp no change'], response: { text: "To update your WhatsApp number:\n1. Go to **Profile** page.\n2. Update the **WhatsApp Number** field.\n3. Click **Save**.\n\nThis number is used for the **Contact Us** button on your store — customers will message you here!", action: { type: 'navigate', label: 'Go to Profile', url: '/dashboard/profile' } }, followUp: ['How to update UPI?', 'How to edit profile?'] },
  { id: 'delivery_settings', category: 'profile', keywords: ['delivery settings','delivery charge','shipping settings','delivery cost set','delivery charge set karo','delivery settings kaise change','shipping charge','delivery fee set karo','free delivery set karo'], response: { text: "To set delivery charges:\n1. Go to **Profile** page.\n2. Find **Delivery Settings** section.\n3. Choose your delivery type:\n   - **Fixed charge** (e.g., ₹50 per order)\n   - **Free above threshold** (e.g., free above ₹500)\n4. Enter the amount and save.", action: { type: 'navigate', label: 'Go to Profile', url: '/dashboard/profile' } }, followUp: ['How to set free delivery?', 'How to update profile?'] },
  { id: 'free_delivery', category: 'profile', keywords: ['free delivery','no delivery charge','delivery free karo','free shipping','delivery charge hatao','free delivery kaise de','muft delivery','zero delivery charge'], response: { text: "To offer free delivery above a certain order value:\n1. Go to **Profile** → **Delivery Settings**.\n2. Set delivery type to **\"Free above threshold\"**.\n3. Set the minimum order amount (e.g., ₹500).\n4. Save.\n\nOrders above that amount will get free delivery!", action: { type: 'navigate', label: 'Go to Profile', url: '/dashboard/profile' } }, followUp: ['How to increase AOV?', 'How to update delivery?'] },
  { id: 'billing_address', category: 'profile', keywords: ['billing address','update address','change address','my address','business address','address update karo','pata badle','billing details','gst number','gst details'], response: { text: "To update your billing address and GST:\n1. Go to **Profile** page.\n2. Scroll to **Billing Details** section.\n3. Update your address, city, state, ZIP code.\n4. Add your **GST number** if applicable.\n5. Save.", action: { type: 'navigate', label: 'Go to Profile', url: '/dashboard/profile' } }, followUp: ['How to get invoices?', 'How to update profile?'] },
  { id: 'change_password', category: 'profile', keywords: ['change password','update password','new password','password change karo','password badle','naya password','password update karo','password reset','password bhool gaya','forgot password','login issue','cant login'], response: { text: "To change or reset your password:\n1. Go to the **Login** page.\n2. Click **\"Forgot Password\"** or **\"Magic Link\"**.\n3. Enter your email.\n4. Check your email for the reset link.\n5. Set a new password.\n\n**Tip:** Use a strong password with letters, numbers, and symbols!", action: { type: 'link', label: 'Reset Password', url: '/forgot-password' } }, followUp: ['I can\'t login', 'Contact support'] },
  { id: 'login_issue', category: 'profile', keywords: ['cant login','login problem','login nahi ho raha','login issue','account access','login error','sign in problem','unable to sign in','access denied','authentication failed'], response: { text: "If you can't login, try these steps:\n1. **Check your email** for the Magic Link.\n2. **Reset your password** using the Forgot Password option.\n3. **Clear browser cookies** and try again.\n4. **Try a different browser** (Chrome works best).\n\nIf nothing works, contact us on WhatsApp!", action: { type: 'whatsapp', label: 'Get Login Help' } }, followUp: ['Reset my password', 'Contact support'] },
  { id: 'change_email', category: 'profile', keywords: ['change email','update email','new email','email change karo','email badle','naya email'], response: { text: "Currently, you cannot change your login email directly. This is for security reasons.\n\nIf you need to change your email, please contact us on WhatsApp and we'll help you migrate your account.", action: { type: 'whatsapp', label: 'Contact Support' } }, followUp: ['Contact support', 'How to update profile?'] },
  { id: 'delete_account', category: 'profile', keywords: ['delete account','delete my account','remove account','account delete karo','mera account hatao','account band karo','close account'], response: { text: "We're sorry to hear that! 😢\n\nTo delete your account, please contact us on WhatsApp. We'll process your request within 24 hours.\n\n⚠️ **Warning:** This permanently deletes all your data including products, orders, and website.", action: { type: 'whatsapp', label: 'Request Account Deletion' } }, followUp: ['Can I pause instead?', 'Contact support'] },
];
