// Website & Editor Domain — 65+ intents (EN + Hindi/Hinglish)
export const websiteIntents = [
  // === PUBLISH ===
  { id: 'publish_website', category: 'website', keywords: ['publish website','go live','launch site','make website live','publish karo','website live karo','website publish kaise kare','site launch karo','website chalu karo','how to publish','make my site live','website activate'], response: { text: "To publish your website:\n1. Go to the **Website/Editor** page.\n2. Make any final changes you want.\n3. Click the **Publish** button in the top right.\n4. Your site will be **live instantly**! 🎉\n\n**Note:** You need an active subscription to publish.", action: { type: 'navigate', label: 'Go to Editor', url: '/dashboard/website' } }, followUp: ['What is my website URL?', 'How to change my template?', 'How to unpublish?'] },
  { id: 'unpublish_website', category: 'website', keywords: ['unpublish website','take down site','make website offline','unpublish karo','website offline karo','website band karo','site hatao','remove website','website down karo'], response: { text: "To unpublish (take offline) your website:\n1. Go to the **Website/Editor** page.\n2. Click the **Unpublish** option.\n3. Your site will go offline, but all your data is **safely preserved**.\n\nYou can republish anytime!", action: { type: 'navigate', label: 'Go to Editor', url: '/dashboard/website' } }, followUp: ['How to republish?', 'Will I lose my data?'] },
  { id: 'preview_website', category: 'website', keywords: ['preview website','preview site','see my website','see my site','preview karo','meri website dikhao','site ka preview','website dekhni hai','how does my site look'], response: { text: "To preview your website:\n1. Go to the **Website/Editor** page.\n2. The editor shows a **live preview** of your site.\n3. To see the full site, click **Preview** or visit your site URL.\n\nYour site URL is: **yourstore.bizvistar.in**", action: { type: 'navigate', label: 'Go to Editor', url: '/dashboard/website' } }, followUp: ['What is my website URL?', 'How to publish?'] },
  { id: 'website_url', category: 'website', keywords: ['website url','my site url','my website link','site link','store url','website ka link','meri website ka link','store ka url','site address','domain','my domain','what is my url','website link kya hai'], response: { text: "Let me check your website details...", action: { type: 'data_query', handler: 'getChatWebsiteStatus' } }, followUp: ['How to change my site URL?', 'How to publish my website?'] },

  // === TEMPLATES ===
  { id: 'change_template', category: 'website', keywords: ['change template','switch template','new template','different template','change theme','switch design','new design','template badle','template change karo','naya template lagao','design change karna hai','theme badle','another template'], response: { text: "To change your website template:\n1. Go to **Website/Editor** page.\n2. Click **Reset Template** or **Change Theme**.\n3. Choose from available templates.\n4. Click **Apply**.\n\n⚠️ **Important:**\n- **Starter plan:** Cannot change template\n- **Pro plan:** 1 change per 30 days\n- **Growth plan:** Unlimited changes\n\nYour content & products are preserved!", action: { type: 'navigate', label: 'Go to Editor', url: '/dashboard/website' } }, followUp: ['What templates are available?', 'Will I lose my data?'] },
  { id: 'available_templates', category: 'website', keywords: ['available templates','all templates','template list','which templates','show templates','template options','template gallery','konse template hain','template dikhao','template ki list'], response: { text: "We have several beautiful templates:\n- **Aurora** — Modern, clean design\n- **Frostify** — Cool, elegant layout\n- **Starter** — Simple, fast-loading\n- And more being added regularly!\n\nYou can preview all templates from the editor.", action: { type: 'navigate', label: 'Browse Templates', url: '/templates' } }, followUp: ['How to change template?', 'Which template is best?'] },
  { id: 'template_limit', category: 'website', keywords: ['template change limit','how often change template','template restriction','kitni baar template badle','template change limit kya hai','template quota'], response: { text: "Template change limits depend on your plan:\n- **Starter:** Cannot change (locked to initial choice)\n- **Pro:** 1 change every 30 days\n- **Growth:** Unlimited changes! 🎉\n\nUpgrade to Growth for maximum flexibility.", action: { type: 'navigate', label: 'View Plans', url: '/pricing' } }, followUp: ['How to upgrade my plan?', 'What is my current plan?'] },
  { id: 'template_recommendation', category: 'website', keywords: ['which template suits me','suggest template','recommend template','best template','which template should i use','konsa template accha hai','template suggest karo','mujhe konsa template lagana chahiye','best template for me','template recommend karo','which template is good','template for my business','suggest me a template','best design for me'], response: { text: "Here's my **template recommendation** based on business type:\n\n🛍️ **Fashion / Clothing / Lifestyle:**\n→ **Aurora** — Modern, image-heavy, great for showcasing products\n\n🧊 **Premium / Tech / Electronics:**\n→ **Frostify** — Cool, elegant, dark-mode capable\n\n🍰 **Food / Bakery / Restaurant:**\n→ **Flavornest** — Warm colors, food-friendly layout\n\n🌸 **Beauty / Wellness / Gifts:**\n→ **Blissly** — Soft, beautiful, pastel-friendly\n\n🔥 **General / Accessories / Home:**\n→ **Flara** — Bold, modern, versatile\n\n**Tip:** Try **Aurora** if you're unsure — it works for almost everything! 🎨", action: { type: 'navigate', label: 'Browse Templates', url: '/templates' } }, followUp: ['Show all templates', 'How to change template?', 'Change my template'] },
  { id: 'template_for_clothing', category: 'website', keywords: ['template for clothing','fashion template','clothing store template','kapde ke liye template','fashion ke liye konsa template','clothing website design'], response: { text: "For a **clothing/fashion** store, I recommend:\n\n🥇 **Aurora** — Clean, modern, image-focused grid. Perfect for showing off outfits.\n🥈 **Flara** — Bold and trendy. Great for streetwear and accessories.\n\nBoth have beautiful product galleries and mobile-optimized layouts!", action: { type: 'navigate', label: 'Browse Templates', url: '/templates' } }, followUp: ['Change my template to Aurora', 'How to change template?'] },
  { id: 'template_for_food', category: 'website', keywords: ['template for food','bakery template','restaurant template','food store template','khane ke liye template','restaurant ke liye','bakery ke liye template','cafe template','sweets template'], response: { text: "For a **food/bakery/restaurant** business, I recommend:\n\n🥇 **Flavornest** — Warm, appetizing design made for food businesses.\n🥈 **Blissly** — Soft, inviting layout. Great for sweets and gifts.\n\nFlavornest has a menu-style layout that's perfect for food items!", action: { type: 'navigate', label: 'Browse Templates', url: '/templates' } }, followUp: ['Change my template to Flavornest', 'How to change template?'] },
  { id: 'template_for_electronics', category: 'website', keywords: ['template for electronics','tech template','gadget template','electronics ke liye template','tech store design','gadget store template'], response: { text: "For an **electronics/tech** store, I recommend:\n\n🥇 **Frostify** — Sleek, modern, premium feel. Ideal for gadgets.\n🥈 **Aurora** — Clean grid layout, great product showcase.\n\nFrostify's dark-mode option looks amazing for tech products!", action: { type: 'navigate', label: 'Browse Templates', url: '/templates' } }, followUp: ['Change my template to Frostify', 'How to change template?'] },

  // === EDIT SECTIONS ===
  { id: 'edit_hero', category: 'website', keywords: ['edit hero','change hero','update hero section','hero text','hero image','banner edit','hero section edit karo','banner change karo','hero text badle','main banner'], response: { text: "To edit the Hero/Banner section:\n1. Go to **Website/Editor**.\n2. Click on the **Hero section** at the top.\n3. Edit the **title**, **subtitle**, and **CTA button** text.\n4. Change the background image if needed.\n5. Click **Save Draft** to preserve changes.", action: { type: 'navigate', label: 'Go to Editor', url: '/dashboard/website' } }, followUp: ['How to change hero image?', 'Suggest a good hero title'] },
  { id: 'edit_about', category: 'website', keywords: ['edit about','about section','about us','company info','about page','about section edit karo','about kaise likhein','company description','about us section'], response: { text: "To edit the About section:\n1. Go to **Website/Editor**.\n2. Scroll to the **About** section.\n3. Click on the text to edit it.\n4. Update your business story and description.\n5. Save your changes.\n\nNeed help writing? Ask me to **\"Write an about section for my business\"**!", action: { type: 'navigate', label: 'Go to Editor', url: '/dashboard/website' } }, followUp: ['Write an about section for me', 'How to edit other sections?'] },
  { id: 'edit_faq', category: 'website', keywords: ['edit faq','add faq','frequently asked questions','faq section','faq edit karo','faq add karo','sawal jawab section','faq kaise badle'], response: { text: "To edit FAQ section:\n1. Go to **Website/Editor**.\n2. Scroll to the **FAQ** section.\n3. Click on any question/answer to edit it.\n4. Add or remove Q&As as needed.\n5. Save your changes.\n\nWant me to **suggest FAQ questions** for your business?", action: { type: 'navigate', label: 'Go to Editor', url: '/dashboard/website' } }, followUp: ['Suggest FAQ questions for my store', 'How to edit testimonials?'] },
  { id: 'edit_testimonials', category: 'website', keywords: ['edit testimonials','reviews section','customer reviews','testimonial edit','testimonials kaise badle','review section edit karo','customer feedback section'], response: { text: "To edit testimonials:\n1. Go to **Website/Editor**.\n2. Scroll to the **Testimonials** section.\n3. Click on any testimonial to edit the quote, author name, etc.\n4. Save your changes.\n\nNeed help? Ask me to **\"Write testimonials for my business\"**!", action: { type: 'navigate', label: 'Go to Editor', url: '/dashboard/website' } }, followUp: ['Write testimonials for me', 'How to edit FAQ?'] },
  { id: 'edit_footer', category: 'website', keywords: ['edit footer','footer section','change footer','footer edit karo','footer badle','footer text change','website footer','footer information'], response: { text: "To edit the footer:\n1. Go to **Website/Editor**.\n2. Scroll to the **Footer** section at the bottom.\n3. Edit the description, links, and social media URLs.\n4. Save your changes.", action: { type: 'navigate', label: 'Go to Editor', url: '/dashboard/website' } }, followUp: ['How to add social media links?', 'How to edit contact info?'] },
  { id: 'edit_contact', category: 'website', keywords: ['edit contact','contact section','contact info','contact page','contact details change','contact kaise badle','phone number add karo','email add karo','contact information update'], response: { text: "To update contact information:\n1. Go to **Profile** settings to update your WhatsApp number and email.\n2. In the **Website/Editor**, edit the contact section directly.\n3. Your WhatsApp number is used for the \"Contact Us\" button on your store.\n\nMake sure your WhatsApp number is correct — customers will message you there!", action: { type: 'navigate', label: 'Go to Profile', url: '/dashboard/profile' } }, followUp: ['How to update WhatsApp number?', 'How to edit footer?'] },

  // === LOGO & BRANDING ===
  { id: 'upload_logo', category: 'website', keywords: ['upload logo','change logo','add logo','brand logo','site logo','logo upload karo','logo badle','naya logo lagao','logo kaise change kare','logo kaise upload kare','brand image'], response: { text: "To upload or change your logo:\n1. Go to **Website/Editor**.\n2. Click on the **Header** section at the top.\n3. Click on the logo area to upload a new image.\n4. Select your logo file.\n5. Save changes.\n\n**Tip:** Use a transparent PNG for best results!", action: { type: 'navigate', label: 'Go to Editor', url: '/dashboard/website' } }, followUp: ['What logo size is recommended?', 'How to change colors?'] },

  // === COLORS & THEME ===
  { id: 'change_colors', category: 'website', keywords: ['change color','theme color','color scheme','brand color','change theme color','color badle','rang badle','color scheme change','color palette','theme ka color badle','website ka color change'], response: { text: "To change your website colors:\n1. Go to **Website/Editor**.\n2. Look for the **Theme/Color** settings in the sidebar.\n3. Choose from the **8 preset color palettes**.\n4. Save your changes.\n\n⚠️ Custom hex codes are not supported yet — only preset palettes are available.", action: { type: 'navigate', label: 'Go to Editor', url: '/dashboard/website' } }, followUp: ['Can I use custom colors?', 'How to change template?'] },
  { id: 'custom_colors', category: 'website', keywords: ['custom color','hex code','own color','brand color code','specific color','custom hex','apna color','custom color code','hex color use karo'], response: { text: "Currently, you can only choose from the **8 preset colors** available in theme settings. Custom hex code support is not available yet.\n\n**Why?** This ensures your site always looks great with professionally designed color palettes!\n\nCustom colors are on our roadmap. 🎨", action: null }, followUp: ['What colors are available?', 'How to change template?'] },

  // === SAVE & REVERT ===
  { id: 'save_draft', category: 'website', keywords: ['save draft','save changes','save website','save karo','changes save karo','draft save karo','website save karo','save my work'], response: { text: "To save your changes:\n1. In the **Website/Editor**, click **Save Draft**.\n2. Your changes are saved but NOT published yet.\n3. To make them live, click **Publish**.\n\n**Note:** Drafts are automatically saved as you work!", action: { type: 'navigate', label: 'Go to Editor', url: '/dashboard/website' } }, followUp: ['How to publish?', 'How to revert changes?'] },
  { id: 'revert_changes', category: 'website', keywords: ['revert changes','undo changes','reset editor','go back to published','original design','changes undo karo','purana wala la wapas','reset karo','revert karo'], response: { text: "To revert to the published version:\n1. Go to **Website/Editor**.\n2. Click **Revert to Published** (or Restart).\n3. This will discard all draft changes and restore the currently live version.\n\n⚠️ Any unsaved draft changes will be lost!", action: { type: 'navigate', label: 'Go to Editor', url: '/dashboard/website' } }, followUp: ['How to save draft?', 'How to publish?'] },

  // === SEO ===
  { id: 'seo_settings', category: 'website', keywords: ['seo','search engine','google ranking','seo settings','meta description','page title','google me aana hai','google pe kaise aaye','seo kaise kare','website ko google pe laye'], response: { text: "**SEO Tips for your BizVistar store:**\n1. Your site slug (URL) matters — keep it short & relevant.\n2. Add a clear **business name** — it becomes your page title.\n3. Write a good **About** section — Google reads this!\n4. Add **product descriptions** — helps Google find your products.\n5. Share your store link on social media for backlinks.\n\nGoogle automatically indexes BizVistar stores within a few days of publishing!", action: null }, followUp: ['How to change my site URL?', 'How to edit About section?'] },

  // === SITE SLUG ===
  { id: 'change_slug', category: 'website', keywords: ['change url','change slug','site url change','website address change','custom url','url badle','link badle','website ka naam badle','site slug change karo','domain change'], response: { text: "To change your site URL (slug):\n1. Go to **Profile** settings.\n2. Find the **Site URL** section.\n3. Enter your new desired URL.\n4. Check availability and save.\n\nYour site will be at: **yourname.bizvistar.in**\n\n**Rules:** Minimum 3 characters, only letters, numbers, and hyphens.", action: { type: 'navigate', label: 'Go to Profile', url: '/dashboard/profile' } }, followUp: ['Is my URL available?', 'How to get a custom domain?'] },
  { id: 'custom_domain', category: 'website', keywords: ['custom domain','own domain','personal domain','buy domain','apna domain','custom domain lagao','own domain use karo','domain connect karo','.com domain','.in domain'], response: { text: "We currently support subdomains: **yourstore.bizvistar.in**\n\nCustom domain support (yourstore.com) is **coming soon**! 🚀\n\nWhen available, you'll be able to connect your own domain purchased from any registrar (GoDaddy, Namecheap, etc.).", action: null }, followUp: ['What is my current URL?', 'How to change my URL?'] },

  // === MOBILE ===
  { id: 'mobile_responsive', category: 'website', keywords: ['mobile responsive','mobile view','phone view','mobile friendly','mobile pe kaisa dikhega','phone pe kaisa hai','mobile design','responsive design','mobile layout'], response: { text: "Yes! All BizVistar templates are **fully mobile responsive**. 📱\n\nYour store automatically adjusts for phones, tablets, and desktops. No extra setup needed!\n\nTo preview the mobile view, simply resize your browser window or visit your site on your phone.", action: null }, followUp: ['How to preview my site?', 'How to change template?'] },

  // === AI CONTENT ===
  { id: 'generate_content', category: 'website', keywords: ['generate content','ai content','auto generate text','ai write','write website content','content generate karo','ai se likhwao','website ka content likhwao','auto content'], response: { text: "To generate AI-powered content for your website:\n1. Go to the **onboarding wizard** or **editor**.\n2. Describe your business in a few words.\n3. Our AI will generate:\n   - Hero title & subtitle\n   - About section\n   - FAQ questions & answers\n   - Testimonials\n   - Feature descriptions\n\nOr just ask me: **\"Write a hero title for my bakery\"**!", action: null }, followUp: ['Write a hero title for me', 'Write an about section for me'] },

  // === SOCIAL MEDIA ===
  { id: 'social_links', category: 'website', keywords: ['social media links','instagram link','facebook link','social links add','social media add karo','instagram add karo','facebook add karo','social link kaise daale'], response: { text: "To add social media links:\n1. Go to **Profile** settings.\n2. Add your **Instagram** and **Facebook** URLs.\n3. Save.\n\nThese links will appear in your website's footer so customers can follow you!", action: { type: 'navigate', label: 'Go to Profile', url: '/dashboard/profile' } }, followUp: ['How to edit footer?', 'How to update profile?'] },
];
